---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: poolboy deploy
  name: poolboy-build

parameters:
- name: GIT_REPO
  value: https://github.com/redhat-gpte-devopsautomation/poolboy.git
- name: SERVICE_NAME
  value: poolboy
- name: NAMESPACE
  value: poolboy

objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ${SERVICE_NAME}
    namespace: ${NAMESPACE}
  spec:
    lookupPolicy:
      local: false

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${SERVICE_NAME}
    namespace: ${NAMESPACE}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${SERVICE_NAME}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: operator
      git:
        uri: ${GIT_REPO}
        ref: master
    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: DockerImage
          name: registry.access.redhat.com/ubi8:latest
    triggers: []
