apiVersion: v1
kind: List
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: resource-claim-operator-anarchy
  rules:
  - apiGroups:
    - gpte.redhat.com
    resources:
    - anarchysubjects
    verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - watch
    - update
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: resource-claim-operator-anarchy
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: resource-claim-operator-anarchy
  subjects:
  - kind: ServiceAccount
    name: resource-claim-operator
    namespace: resource-claim-operator
