---
apiVersion: poolboy.gpte.redhat.com/v1
kind: ResourceProvider
metadata:
  name: anarchy-lab-env-configmap
  namespace: poolboy
spec:
  match:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      annotations:
        poolboy.gpte.redhat.com/resource-provider-name: anarchy-lab-env-configmap
  default:
    data:
      gateway.sh: ''
      terminal.sh: |
        {%: raw -:%}
        GUID={{: resource_handle.metadata.name[-5:] :}}
        export GUID
        {%: endraw :%}
      workshop.sh: |
        {%: raw -:%}
        GUID={{: resource_handle.metadata.name[-5:] :}}
        export GUID
        {%: endraw :%}
  override:
    metadata:
      namespace: '{{: resource_claim.metadata.namespace :}}'
  resourceRequiresClaim: True
  validation:
    openAPIV3Schema:
      type: object
      required:
      - apiVersion
      - kind
      - metadata
      additionalProperties: false
      properties:
        apiVersion:
          type: string
          enum:
          - v1
        kind:
          type: string
          enum:
          - ConfigMap
        metadata:
          type: object
          properties:
            annotations:
              type: object
              additionalProperties:
                type: string
            labels:
              type: object
              additionalProperties:
                type: string
            name:
              type: string
        data:
          type: object
          additionalProperties:
            type: string
