---
name: pull-request
on:
  pull_request:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    #- name: Static tests
    #  run: |

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build example from s2i image
      uses: docker/build-push-action@v2
      with:
        push: false
        repository: poolboy
        tags: ${{ github.sha }}

    #- name: Test image
    #  run: |
